### ISSUE TITLE
Link to generated docs from github Readme

### ISSUE THREAD

**Issue by simp4t7** [ptmphuong/dockerfile-builder#4]
See a bunch of repos that have some autogenerated links to the generated docs / creates.io CI stuff. Would be nice.

**Comment by simp4t7** [comment]
Found this as an example:

[![Build status](https://github.com/tokio-rs/axum/actions/workflows/CI.yml/badge.svg?branch=main)](https://github.com/tokio-rs/axum/actions/workflows/CI.yml)
[![Crates.io](https://img.shields.io/crates/v/axum)](https://crates.io/crates/axum)
[![Documentation](https://docs.rs/axum/badge.svg)](https://docs.rs/axum)

Just docs and crates.io would be good for now.

**Comment by ptmphuong** [comment]
thanks. updated in e74bd8439a5805c6734f0db3610b28a11942cd63
