### ISSUE TITLE
Bug with CopyBuilder from method

### ISSUE THREAD

**Issue by simp4t7** [ptmphuong/dockerfile-builder#5]
`.push(CopyBuilder::builder().from("planner").src("recipe.json").dest("recipe.json").build()?)` should produce: `COPY --from=planner recipe.json recipe.json`

However, it returns `COPY --chmod=planner recipe.json recipe.json`

Should be an easy fix.

**Comment by ptmphuong** [comment]
fix in 649d8db46b3e042d2ab78ffc4af4b845fc18a16b
